= About HyperShift
include::_attributes.adoc[]
:profile: telco-hypershift-baremetal-lab

HyperShift is middleware for hosting OpenShift control planes at scale that decreases the cost and time to provision them, and increases portability across clouds with a strong separation of concerns between management and workloads.

Clusters are fully compliant OpenShift Container Platform (OCP) clusters and are compatible with standard OCP and Kubernetes toolchains.

When using HyperShift, OpenShift is deployed on top of an existing cluster by creating the following objects:

* *hostedcluster*  This represents the cluster and in particular the control plane components that will be "hosted" in a dedicated cluster
* *nodepool* This represents the workers part of our hostedcluster. Its spec contains the following elements:
  ** release image, which might be different from the one specified in the hosted cluster.
  ** platform, which indicates which target platform the workers might have. Valid values can either be aws, kubevirt, agent, none,...
  ** replicas, which indicates how many nodes we want to deploy

Both objects contain a platform attribute as part of their spec, and components get deployed depending on the target platform. For instance, if we use Kubevirt, a component will be deployed so that VMs get provisioned depending on the `replicas` spec of the nodepool.

In this lab we are using the agent provider, suitable for bare metal deployments. It relies on the assisted service having already been deployed in the target cluster.
