= Introduction to the lab environment
include::_attributes.adoc[]
:profile: hypershift-baremetal-lab

Before jumping into the hands-on sections let's get familiar with the lab environment we have available.

CAUTION: The following lab sections rely on having a lab environment accessible in order to do the hands-on work. If you're a Red Hatter you can order a lab environment already setup for you on the https://demo.redhat.com[Red Hat Demo Platform]. You just need to order the lab named `Hosted Control Planes on Baremetal`. Notice that it has a cost of ~ $56 to run through the lab. When the lab is launched, by default you will have 12 hours to complete it before it is destroyed. The estimated time to finish the lab might look like 5 hours total (40m provisioning time, 3h lab work, 1h20m margin). If you need further time, it can be manually extended up to 24h in total. If you still need to deploy a lab environment, follow the guide available xref:lab-setup.adoc[here].

[#openshift-management-cluster]
== OpenShift Management Cluster

An OpenShift cluster is running on the infrastructure host, you can reach it out at https://console-openshift-console.apps.management.hypershift.lab from your browser and at https://api.management.hypershift.lab:6443 from your `oc` client.

Credentials for the OCP cluster (htpassidp provider):

* Username: `admin` 
* Password: The password is randomly generated for each environment, and can be found in the e-mail you received when the lab was ready.
