= Lab Setup
include::_attributes.adoc[]
:profile: hypershift-baremetal-lab

This section describes how to deploy your own lab environment.

CAUTION: If you are a Red Hatter, you can order a lab environment on the https://demo.redhat.com[Red Hat Demo Platform]. You just need to order the lab named `Hosted Control Planes on Baremetal`.

[#lab-requirements]
== Lab Requirements

RHEL {byow-rhel} box with access to the Internet. This lab relies on KVM, so you need to have the proper virtualization packages already installed. It is highly recommended to use a bare-metal host. Our lab environment has the following specs:

* 64 CPUs (with or without hyperthreading)
* 200GiB Memory.
* 1 TiB storage.

IMPORTANT: These instructions have been tested in a RHEL {rhel-version}, we cannot guarantee that other operating systems (even RHEL-based) will work. We won't be providing support out of RHEL {byow-rhel}.

These are the steps to install the required packages on a RHEL {rhel-version} server:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf -y install libvirt libvirt-daemon-driver-qemu qemu-kvm
usermod -aG qemu,libvirt $(id -un)
newgrp libvirt
systemctl enable libvirtd --now
-----

[#lab-deployment]
== Lab Deployment

IMPORTANT: All the steps in the below sections must be run as `root` user on the hypervisor host.

[#install-kcli]
=== Install kcli

We use https://github.com/karmab/kcli[kcli] to do several things, like managing VMs, deploying the first OCP cluster, etc. Additional kcli documentation can be found at `https://kcli.readthedocs.io`

IMPORTANT: Below commands must be executed from the hypervisor host as root if not specified otherwise.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf -y copr enable karmab/kcli
dnf -y install {epel-release}
dnf -y install kcli bash-completion vim jq tar git python3-cherrypy
-----

[#install-oc-kubectl]
=== Install oc/kubectl CLIs

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli download oc -P version=stable -P tag='{tooling-version}'
mv oc /usr/local/bin/
-----

[#configure-lab-network]
=== Configure Lab Network

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli create network -c 192.168.125.0/24 -P dhcp=false -P dns=false --domain hypershift.lab hypershiftlab
-----

[#configure-local-dns-dhcp-server]
=== Configure Local DNS/DHCP Server

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf -y install dnsmasq policycoreutils-python-utils
mkdir -p /opt/dnsmasq/include.d/
curl -sL https://raw.githubusercontent.com/RHsyseng/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/dnsmasq/dnsmasq.conf -o /opt/dnsmasq/dnsmasq.conf
curl -sL https://raw.githubusercontent.com/RHsyseng/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/dnsmasq/upstream-resolv.conf -o /opt/dnsmasq/upstream-resolv.conf
curl -sL https://raw.githubusercontent.com/RHsyseng/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/dnsmasq/management.ipv4 -o /opt/dnsmasq/include.d/management.ipv4
curl -sL https://raw.githubusercontent.com/RHsyseng/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/dnsmasq/hosted.ipv4 -o /opt/dnsmasq/include.d/hosted.ipv4
curl -sL https://raw.githubusercontent.com/RHsyseng/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/dnsmasq/infrastructure-host.ipv4 -o /opt/dnsmasq/include.d/infrastructure-host.ipv4
curl -sL https://raw.githubusercontent.com/RHsyseng/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/dnsmasq/dnsmasq-virt.service -o /etc/systemd/system/dnsmasq-virt.service
touch /opt/dnsmasq/hosts.leases
semanage fcontext -a -t dnsmasq_etc_t '/opt/dnsmasq(/.*)?'         # semanage commands order is important
semanage fcontext -a -t dnsmasq_lease_t /opt/dnsmasq/hosts.leases  # senabage commands order is important
restorecon -vr /opt/dnsmasq/
sed -i "s/UPSTREAM_DNS/1.1.1.1/" /opt/dnsmasq/upstream-resolv.conf
systemctl daemon-reload
systemctl enable dnsmasq-virt --now
systemctl mask dnsmasq
-----

[#configure-local-dns-as-primary-server]
=== Configure Local DNS as Primary Server

The default upstream DNS is set to 1.1.1.1 in `/opt/dnsmasq/upstream-resolv.conf`. There might be cases in your local environment where the hypervisor may not reach it. So, notice that you must change it to a different DNS that allows you to resolve public hostnames. Once changed, remember to restart the dnsmasq-virt service.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
curl -L https://raw.githubusercontent.com/RHsyseng/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/hypervisor/forcedns -o /etc/NetworkManager/dispatcher.d/forcedns
chmod +x /etc/NetworkManager/dispatcher.d/forcedns
systemctl restart NetworkManager
/etc/NetworkManager/dispatcher.d/forcedns
-----

[#disable-firewall]
=== Disable Firewall

You can also create the required rules in the firewall if you want, but for the sake of simplicity we are disabling the firewall.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
systemctl disable firewalld iptables
systemctl stop firewalld iptables
iptables -F
systemctl restart libvirtd
-----

[#install-ksushy-tool]
=== Install KSushy Tool

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli create sushy-service --ssl --port 9000 --bootonce
systemctl daemon-reload
systemctl enable ksushy --now
-----

[#configure-ntp-server]
=== Configure NTP Server

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf install chrony -y
cat <<EOF > /etc/chrony.conf
server time.cloudflare.com iburst
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
keyfile /etc/chrony.keys
leapsectz right/UTC
logdir /var/log/chrony
bindcmdaddress ::
allow 192.168.125.0/24
EOF
systemctl enable chronyd --now
-----
[#configure-showroom-app]
=== Configure Showroom APP

Showroom is a WebAPP consisting of different services that will be used to expose the lab content and a terminal and a browser running on the hypervisor host, that way uses can consume the lab from their browser without extra requirements.

First we need to create a user that the students will use to connect to the hypervisor terminal, we recommend an unprivileged user.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
useradd lab-user -G libvirt
passwd lab-user
-----

Make sure the new user can use rootless podman:

WARNING: Below command may fail with `ERRO[0000] running `/usr/bin/newuidmap 66372 0 1000 1 1 100000 65536`: newuidmap: write to uid_map failed: Operation not permitted`.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
su - lab-user
podman version
-----

If above command failed, you need to either configure root-less podman or run podman as root.

Now that lab-user is configured, make sure you continue to run the next commands as root.

Generate lab content on the hypervisor host:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
HYPERVISOR_PUBLIC_HOSTNAME=<PUT_HERE_PUBLIC_HOSTNAME_OR_IP>
mkdir -p /opt/showroom
git clone -b {branch} https://github.com/RHsyseng/hypershift-baremetal-lab.git /opt/showroom/lab-repo/
podman run --rm -v /opt/showroom/lab-repo:/antora:z quay.io/rhsysdeseng/showroom:antora-v3.0.0 site.yml
mkdir -p /opt/showroom/lab-content
cp -pr /opt/showroom/lab-repo/gh-pages/* /opt/showroom/lab-content/
curl -sL https://raw.githubusercontent.com/{repo_user}/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/showroom/webfiles/index.html -o /opt/showroom/lab-content/index.html
curl -sL https://raw.githubusercontent.com/{repo_user}/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/showroom/webfiles/split.css -o /opt/showroom/lab-content/split.css
curl -sL https://raw.githubusercontent.com/{repo_user}/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/showroom/webfiles/tabs.css -o /opt/showroom/lab-content/tabs.css
curl -sL https://raw.githubusercontent.com/{repo_user}hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/showroom/webfiles/tabs.js -o /opt/showroom/lab-content/tabs.js
sed -i "s/<CHANGEME_LAB_VERSION>/{lab-major-version}/" /opt/showroom/lab-content/index.html
sed -i "s/<CHANGEME_HYPERVISOR_PUBLIC_HOSTNAME>/$HYPERVISOR_PUBLIC_HOSTNAME/" /opt/showroom/lab-content/index.html
-----

Run the apache that exposes lab content:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
curl -sL https://raw.githubusercontent.com/{repo_user}/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/showroom/podman-showroom-apache.service -o /etc/systemd/system/podman-showroom-apache.service
systemctl daemon-reload
systemctl enable podman-showroom-apache --now
-----

Run the web terminal:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
LAB_USER_PWD=<PUT_HERE_LAB_USER_PASSWORD>
curl -sL https://raw.githubusercontent.com/{repo_user}/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/showroom/podman-showroom-wetty.service -o /etc/systemd/system/podman-showroom-wetty.service
sed -i "s/<CHANGEME_LAB_USER>/lab-user/" /etc/systemd/system/podman-showroom-wetty.service
sed -i "s/<CHANGEME_LAB_USER_PWD>/$LAB_USER_PWD/" /etc/systemd/system/podman-showroom-wetty.service
systemctl daemon-reload
systemctl enable podman-showroom-wetty --now
-----

Run the firefox browser:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
HTPASS_PASSWORD=<PUT_HERE_A_PASSWORD>
curl -sL https://raw.githubusercontent.com/{repo_user}/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/showroom/podman-showroom-firefox.service -o /etc/systemd/system/podman-showroom-firefox.service
curl -sL https://raw.githubusercontent.com/{repo_user}/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/showroom/firefox-config.tar.gz -o /tmp/firefox-config.tar.gz
tar xfz /tmp/firefox-config.tar.gz -C /opt/showroom/
rm -f /tmp/firefox-config.tar.gz
sed -i "s/<CHANGEME_LAB_USER>/lab-user/" /etc/systemd/system/podman-showroom-firefox.service
sed -i "s/<CHANGEME_LAB_USER_PWD>/$HTPASS_PASSWORD/" /etc/systemd/system/podman-showroom-firefox.service
systemctl daemon-reload
systemctl enable podman-showroom-firefox --now
-----

Run the reverse proxy:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
HTPASS_USER=$(echo $HTPASS_PASSWORD | htpasswd -i -n lab-user)
HYPERVISOR_PUBLIC_HOSTNAME=<PUT_HERE_PUBLIC_HOSTNAME_OR_IP>
curl -sL https://raw.githubusercontent.com/{repo_user}/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/showroom/podman-showroom-traefik.service -o /etc/systemd/system/podman-showroom-traefik.service
curl -sL https://raw.githubusercontent.com/{repo_user}/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/showroom/traefik-config.tar.gz -o /tmp/traefik-config.tar.gz
mkdir -p /opt/showroom/traefik
tar xfz /tmp/traefik-config.tar.gz -C /opt/showroom/traefik/
rm -f /tmp/traefik-config.tar.gz
sed -i "s|<CHANGEME_HTPASS_USER>|$HTPASS_USER|" /opt/showroom/traefik/config/traefik/dynamic_config.yml
sed -i "s/<CHANGEME_HYPERVISOR_PUBLIC_HOSTNAME>/$HYPERVISOR_PUBLIC_HOSTNAME/" /opt/showroom/traefik/config/traefik/dynamic_config.yml
systemctl daemon-reload
systemctl enable podman-showroom-traefik --now
-----

At this point we can access our hypervisor to get the Showroom app, this URL is the one the student will use with the credentials we configured. Example url: `https://hypervisor.example.com/content/`.

[#create-openshift-nodes-vms]
=== Create Hosted Cluster Nodes VMs

Before running the following commands, make sure you have generated a SSH key pair in your default location `~/.ssh/`. That SSH key will allow you to connect to the VMs you are about to create:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli create pool -p /var/lib/libvirt/images default
kcli create vm -P start=False -P uefi_legacy=true -P plan=lab -P memory=24000 -P numcpus=12 -P disks=[200,200] -P nets=['{"name": "hypershiftlab", "mac": "aa:aa:aa:aa:02:01"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0201 -P name=hosted-worker0
kcli create vm -P start=False -P uefi_legacy=true -P plan=lab -P memory=24000 -P numcpus=12 -P disks=[200,200] -P nets=['{"name": "hypershiftlab", "mac": "aa:aa:aa:aa:02:02"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0202 -P name=hosted-worker1
kcli create vm -P start=False -P uefi_legacy=true -P plan=lab -P memory=24000 -P numcpus=12 -P disks=[200,200] -P nets=['{"name": "hypershiftlab", "mac": "aa:aa:aa:aa:02:03"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0203 -P name=hosted-worker2
-----

If you need or want to connect to any of the VMs you can do so by just executing:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli ssh <VM_name>
-----

[#deploy-openshift-management-cluster]
=== Deploy OpenShift Management Cluster

IMPORTANT: This step requires a valid OpenShift Pull Secret placed in /root/openshift_pull.json. Notice that you can replace the admin or developer's password shown below for any other.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
curl -sL https://raw.githubusercontent.com/RHsyseng/hypershift-baremetal-lab/{branch}/lab-materials/lab-env-data/management-cluster/management.yml -o /root/management.yml
sed -i "s/CHANGE_ADMIN_PWD/admin/" management.yml
sed -i "s/CHANGE_DEV_PWD/developer/" management.yml
kcli create cluster openshift --pf management.yml --force
-----

This will take around 30-45m to complete, the command will output the deployment steps.

If the installation fails for whatever reason, you will need to delete all the VMs that were created and execute the same procedure again. So, first remove the plans, which actually will remove all VMs:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----

# kcli list plan
+------------+-------------------------------------------------------------------+
|    Plan    |                                Vms                                |
+------------+-------------------------------------------------------------------+
|    lab     |            hosted-worker0,hosted-worker1,hosted-worker2           |
| management | management-ctlplane-0,management-ctlplane-1,management-ctlplane-2 |
+------------+-------------------------------------------------------------------+

# kcli delete plan management lab -y
management-installer deleted on local!
Plan management deleted!
hosted-worker0 deleted on local!
hosted-worker1 deleted on local!
hosted-worker2 deleted on local!
management-ctlplane-0 deleted on local!
management-ctlplane-1 deleted on local!
management-ctlplane-2 deleted on local!
Plan lab deleted!
-----

And then create the VMs again as explained in the previous section link:lab-setup.html#create-openshift-nodes-vms[Deploy OpenShift Hub Cluster].

[#check-openshift-management-cluster]
=== Check OpenShift Management Cluster

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
export KUBECONFIG=~/.kcli/clusters/management/auth/kubeconfig
oc get nodes
-----

[console-input]
[source,bash,subs="attributes+,+macros"]
-----
NAME                                   STATUS   ROLES                         AGE   VERSION
management-ctlplane-0.hypershift.lab   Ready    control-plane,master,worker   39m   {management-cluster-kubeversion}
management-ctlplane-1.hypershift.lab   Ready    control-plane,master,worker   39m   {management-cluster-kubeversion}
management-ctlplane-2.hypershift.lab   Ready    control-plane,master,worker   39m   {management-cluster-kubeversion}
-----

Finally, remove the kubeadmin user:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
oc -n kube-system delete secret kubeadmin
-----
