= Lab Setup
include::_attributes.adoc[]
:profile: telco-hypershift-baremetal-lab

This section describes how to deploy your own lab environment.

CAUTION: If you are a Red Hatter, you can order a lab environment on the https://demo.redhat.com[Red Hat Demo Platform]. You just need to order the lab named `Telco Hypershift Deployment on OpenShift`.

[#lab-requirements]
== Lab Requirements

RHEL 8.X box with access to the Internet. This lab relies on KVM, so you need to have the proper virtualization packages already installed. It is highly recommended to use a bare-metal host. Our lab environment has the following specs:

* 48 CPUs.
* 200GiB Memory.
* 1 TiB storage.

IMPORTANT: These instructions have been tested in RHEL 8.X, we cannot guarantee that other operating systems (even RHEL-based) will work. We won't be providing support out of RHEL 8.X.

These are the steps to install the required packages on a RHEL 8.X server:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
yum -y install libvirt libvirt-daemon-driver-qemu qemu-kvm
usermod -aG qemu,libvirt $(id -un)
newgrp libvirt
systemctl enable --now libvirtd
-----

[#install-kcli]
== Install Kcli

We use https://github.com/karmab/kcli[kcli] to do several things, like managing VMs, deploying the first OCP cluster, etc. Additional kcli documentation can be found here https://kcli.readthedocs.io[here]

IMPORTANT: Below commands must be executed from the hypervisor host as root if not specified otherwise.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf -y copr enable karmab/kcli
dnf -y install kcli
kcli create sushy-service
kcli create pool -p /var/lib/libvirt/images default
-----

[#create-baremetal-like-vms]
=== Create Baremetal like VMs

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli create vm -P uefi_legacy=true -P start=false -P memory=20480 -P numcpus=16 -P disks=['{"size": 200, "interface": "sata"}'] -P nets=['{"name": "default", "mac": "aa:aa:aa:bb:bb:90"}'] -c 2 lab-assisted
-----

Expected output

```
lab-assisted-0 created on local
lab-assisted-1 created on local
```

[#create-dns-entries]
=== Create DNS Entries

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli create dns -d karmalabs.corp -i 192.168.122.253 -a console-openshift-console.apps.basecluster -a oauth-openshift.apps.basecluster -a prometheus-k8s-openshift-monitoring.apps.basecluster -a assisted-image-service-multicluster-engine.apps.basecluster -a assisted-service-multicluster-engine.apps.basecluster -a ignition-server-clusters-myhypershift.apps.basecluster -a ovnkube-sbdb-clusters-myhypershift.apps.basecluster api.basecluster
kcli create dns -d karmalabs.corp -i 192.168.122.252 -a console-openshift-console.apps.myhypershift -a prometheus-k8s-openshift-monitoring.apps.myhypershift -a canary-openshift-ingress-canary.apps.myhypershift oauth-openshift.apps.myhypershift
-----

Expected output

```
Creating alias entries for console-openshift-console.apps.basecluster oauth-openshift.apps.basecluster prometheus-k8s-openshift-monitoring.apps.basecluster assisted-image-service-multicluster-engine.apps.basecluster assisted-service-multicluster-engine.apps.basecluster
Creating dns entry for api.basecluster.karmalabs.corp in network default
Creating alias entries for console-openshift-console.apps.myhypershift oauth-openshift.apps.myhypershift prometheus-k8s-openshift-monitoring.apps.myhypershift
Creating dns entry for api-int.myhypershift.karmalabs.corp in network default
```

[#install-base-cluster]
== Install Base Cluster

IMPORTANT: This step requires a valid OpenShift Pull Secret placed in /root/openshift_pull.json. Notice that you can replace the admin or developer's password shown below for any other.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli create cluster openshift -P clusterprofile=sample-openshift-sno basecluster
-----

Expected Ouput:

```
Deploying on client local
Deploying cluster basecluster
Using stable version
Using 192.168.122.253 as api_ip
Setting domain to 192-168-122-253.sslip.io
Downloading openshift-install from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.13
Move downloaded openshift-install somewhere in your PATH if you want to reuse it
Using installer version 4.13.0
Grabbing image rhcos-413.92.202305021736-0-openstack.x86_64.qcow2 from url https://rhcos.mirror.openshift.com/art/storage/prod/streams/4.13-9.2/builds/413.92.202305021736-0/x86_64/rhcos-413.92.202305021736-0-openstack.x86_64.qcow2.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1111M  100 1111M    0     0   105M      0  0:00:10  0:00:10 --:--:--  109M
Image rhcos-413.92.202305021736-0-openstack.x86_64.qcow2 Added
Using image rhcos-413.92.202305021736-0-openstack.x86_64.qcow2
INFO Consuming Install Config from target directory
WARNING Making control-plane schedulable by setting MastersSchedulable to true for Scheduler cluster settings
INFO Manifests created in: /root/.kcli/clusters/basecluster/manifests and /root/.kcli/clusters/basecluster/openshift
Injecting manifest manifests/disable_ntp.yml
Forcing router pods on ctlplanes since sslip is set and api_ip will be used for ingress
INFO Consuming Master Machines from target directory
INFO Consuming Worker Machines from target directory
INFO Consuming Openshift Manifests from target directory
INFO Consuming Common Manifests from target directory
INFO Consuming OpenShift Install (Manifests) from target directory
INFO Ignition-Configs created in: /root/.kcli/clusters/basecluster and /root/.kcli/clusters/basecluster/auth
Using keepalived virtual_router_id 231
Using 192.168.122.253 for api vip....
Deploying bootstrap
Deploying Vms...
Merging ignition data from existing /root/.kcli/clusters/basecluster/bootstrap.ign for basecluster-bootstrap
basecluster-bootstrap deployed on local
Deploying ctlplanes
Deploying Vms...
Merging ignition data from existing /root/.kcli/clusters/basecluster/ctlplane.ign for basecluster-ctlplane-0
basecluster-ctlplane-0 deployed on local
INFO Waiting up to 20m0s (until 9:01AM) for the Kubernetes API at https://api.basecluster.192-168-122-253.sslip.io:6443...
INFO API v1.26.3+b404935 up
INFO Waiting up to 30m0s (until 9:13AM) for bootstrapping to complete...
INFO It is now safe to remove the bootstrap resources
INFO Time elapsed: 13m24s
Launching install-complete step. It will be retried one extra time in case of timeouts
INFO Waiting up to 40m0s (until 9:35AM) for the cluster at https://api.basecluster.192-168-122-253.sslip.io:6443 to initialize...
INFO Checking to see if there is a route at openshift-console/console...
INFO Install complete!
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/root/.kcli/clusters/basecluster/auth/kubeconfig'
INFO Access the OpenShift web-console here: https://console-openshift-console.apps.basecluster.192-168-122-253.sslip.io
INFO Login to the console with user: "kubeadmin", and password: "Rr4VH-tojC9-CECQM-7GUkM"
INFO Time elapsed: 8m47s
Deleting basecluster-bootstrap
Adding app lvms-operator
Forcing namespace to openshift-storage
namespace/openshift-storage created
operatorgroup.operators.coreos.com/lvms-operator-operatorgroup created
subscription.operators.coreos.com/lvms-operator created
Waiting for CRD LVMCluster to be created
Waiting for CRD LVMCluster to be created
Waiting for CRD LVMCluster to be created
Waiting for CRD LVMCluster to be created
Waiting for CRD LVMCluster to be created
lvmcluster.lvm.topolvm.io/lvmcluster created
Waiting for the storageclass to be created
Waiting for the storageclass to be created
Waiting for the storageclass to be created
Waiting for the storageclass to be created
Waiting for the storageclass to be created
Waiting for the storageclass to be created
Waiting for the storageclass to be created
NAME                 PROVISIONER   RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
lvms-vg1 (default)   topolvm.io    Delete          WaitForFirstConsumer   true                   0s
storageclass.storage.k8s.io/lvms-vg1 patched (no change)
Adding app users
Adding dev user dev with password dev
Adding admin user admin with password admin
Warning: resource oauths/cluster is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
oauth.config.openshift.io/cluster configured
secret/htpass-secret created
Granting cluster-admin role to admin
Warning: User 'admin' not found
clusterrole.rbac.authorization.k8s.io/cluster-admin added: "admin"
Creating cluster-admins group
group.user.openshift.io/cluster-admins created
Adding admin user admin to cluster-admins group
group.user.openshift.io/cluster-admins added: "admin"
```

Once the installation is finished, you can interact with the resulting cluster by running `export KUBECONFIG=$HOME/.kcli/clusters/basecluster/auth/kubeconfig`

[#configure-access-to-cluster-apps]
=== Configure Access to Cluster Apps

In order to access the cluster, we will deploy an HAProxy that will be listening on the public interface of the Hypervisor host using the following haproxy.cfg

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
global
    log         127.0.0.1 local2
    maxconn     4000
    daemon

defaults
    mode                    tcp
    log                     global
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

listen stats-50000
    bind :50000
    mode            http
    log             global
    maxconn 10
    timeout client  100s
    timeout server  100s
    timeout connect 100s
    stats enable
    stats hide-version
    stats refresh 30s
    stats show-node
    stats auth admin:password
    stats uri  /haproxy?stats

frontend apis-6443
    bind :6443
    mode tcp
    tcp-request inspect-delay 5s
    tcp-request content accept if { req_ssl_hello_type 1 }
    acl ACL_basecluster req_ssl_sni -i api.basecluster.karmalabs.corp
    use_backend be_api_basecluster_6443 if ACL_basecluster

frontend routers-http-80
    bind :80
    mode http
    acl ACL_basecluster hdr(host) -m reg -i ^[^\.]+\.apps\.basecluster\.karmalabs\.corp
    acl ACL_hypershift hdr(host) -m reg -i ^[^\.]+\.apps\.myhypershift\.karmalabs\.corp
    use_backend be_ingress_basecluster_80 if ACL_basecluster
    use_backend be_ingress_hypershift_80 if ACL_hypershift

frontend routers-https-443
    bind :443
    mode tcp
    tcp-request inspect-delay 5s
    tcp-request content accept if { req_ssl_hello_type 1 }
    acl ACL_basecluster req_ssl_sni -m reg -i ^[^\.]+\.apps\.basecluster\.karmalabs\.corp
    acl ACL_hypershift req_ssl_sni -m reg -i ^[^\.]+\.apps\.myhypershift\.karmalabs\.corp
    use_backend be_ingress_basecluster_443 if ACL_basecluster
    use_backend be_ingress_hypershift_443 if ACL_hypershift

backend be_api_basecluster_6443
    mode tcp
    balance source
    option ssl-hello-chk
    server basecluster 192.168.122.253:6443 check inter 1s

backend be_ingress_basecluster_80
    mode http
    balance hdr(Host)
    hash-type consistent
    option forwardfor
    http-send-name-header Host
    server basecluster 192.168.122.253:80 check inter 1s

backend be_ingress_basecluster_443
    mode tcp
    balance source
    option ssl-hello-chk
    server basecluster 192.168.122.253:443 check inter 1s

backend be_ingress_hypershift_80
    mode http
    balance hdr(Host)
    hash-type consistent
    option forwardfor
    http-send-name-header Host
    server myhypershift 192.168.122.252:80 check inter 1s

backend be_ingress_hypershift_443
    mode tcp
    balance source
    option ssl-hello-chk
    server myhypershift 192.168.122.252:443 check inter 1s
-----

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf install haproxy -y
semanage port -a -t http_port_t -p tcp 6443
cp scripts/HAPROXY/haproxy.cfg -o /etc/haproxy/haproxy.cfg
systemctl enable haproxy --now
-----

You will need to add the following entries to your /etc/hosts file:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
<HYPERVISOR_REACHABLE_IP> api.basecluster.karmalabs.corp console-openshift-console.apps.basecluster.karmalabs.corp oauth-openshift.apps.basecluster.karmalabs.corp prometheus-k8s-openshift-monitoring.apps.basecluster.karmalabs.corp console-openshift-console.apps.myhypershift.karmalabs.corp oauth-openshift.apps.myhypershift.karmalabs.corp prometheus-k8s-openshift-monitoring.apps.myhypershift.karmalabs.corp
-----
