= Lab Setup
include::_attributes.adoc[]
:profile: telco-hypershift-baremetal-lab

This section describes how to deploy your own lab environment.

CAUTION: If you are a Red Hatter, you can order a lab environment on the https://demo.redhat.com[Red Hat Demo Platform]. You just need to order the lab named `Hosted Control Planes for Telcos`.

[#lab-requirements]
== Lab Requirements

RHEL 8.X box with access to the Internet. This lab relies on KVM, so you need to have the proper virtualization packages already installed. It is highly recommended to use a bare-metal host. Our lab environment has the following specs:

* 64 CPUs (with or without hyperthreading)
* 200GiB Memory.
* 1 TiB storage.
+-
IMPORTANT: These instructions have been tested in a RHEL 8.7, we cannot guarantee that other operating systems (even RHEL-based) will work. We won't be providing support out of RHEL 8.

These are the steps to install the required packages on a RHEL 8.7 server:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
yum -y install libvirt libvirt-daemon-driver-qemu qemu-kvm
usermod -aG qemu,libvirt $(id -un)
newgrp libvirt
systemctl enable --now libvirtd
-----

[#lab-deployment]
== Lab Deployment

IMPORTANT: All the steps in the below sections must be run as `root` user on the hypervisor host.

[#install-kcli]
=== Install kcli

We use https://github.com/karmab/kcli[kcli] to do several things, like managing VMs, deploying the first OCP cluster, etc. Additional kcli documentation can be found at `https://kcli.readthedocs.io`

IMPORTANT: Below commands must be executed from the hypervisor host as root if not specified otherwise.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf -y copr enable karmab/kcli
dnf -y install kcli bash-completion vim jq tar git
-----

[#install-oc-kubectl]
=== Install oc/kubectl CLIs

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli download oc -P version=stable -P tag='4.13'
kcli download kubectl -P version=stable -P tag='4.13'
mv kubectl oc /usr/bin/
-----

[#configure-lab-network]
=== Configure Lab Network

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli create network -c 192.168.125.0/24 --nodhcp --domain hypershift.lab hypershiftlab
-----

[#configure-local-dns-dhcp-server]
=== Configure Local DNS/DHCP Server

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf -y install dnsmasq policycoreutils-python-utils
mkdir -p /opt/dnsmasq/include.d/
curl -sL https://raw.githubusercontent.com/RHsyseng/telco-hypershift-baremetal-lab/lab-4.13/lab-materials/lab-env-data/dnsmasq/dnsmasq.conf -o /opt/dnsmasq/dnsmasq.conf
curl -sL https://raw.githubusercontent.com/RHsyseng/telco-hypershift-baremetal-lab/lab-4.13/lab-materials/lab-env-data/dnsmasq/upstream-resolv.conf -o /opt/dnsmasq/upstream-resolv.conf
curl -sL https://raw.githubusercontent.com/RHsyseng/telco-hypershift-baremetal-lab/lab-4.13/lab-materials/lab-env-data/dnsmasq/management.ipv4 -o /opt/dnsmasq/include.d/management.ipv4
curl -sL https://raw.githubusercontent.com/RHsyseng/telco-hypershift-baremetal-lab/lab-4.13/lab-materials/lab-env-data/dnsmasq/hosted.ipv4 -o /opt/dnsmasq/include.d/hosted.ipv4
curl -sL https://raw.githubusercontent.com/RHsyseng/telco-hypershift-baremetal-lab/lab-4.13/lab-materials/lab-env-data/dnsmasq/infrastructure-host.ipv4 -o /opt/dnsmasq/include.d/infrastructure-host.ipv4
curl -sL https://raw.githubusercontent.com/RHsyseng/telco-hypershift-baremetal-lab/lab-4.13/lab-materials/lab-env-data/dnsmasq/dnsmasq-virt.service -o /etc/systemd/system/dnsmasq-virt.service
touch /opt/dnsmasq/hosts.leases
semanage fcontext -a -t dnsmasq_lease_t /opt/dnsmasq/hosts.leases
restorecon /opt/dnsmasq/hosts.leases
sed -i "s/UPSTREAM_DNS/1.1.1.1/" /opt/dnsmasq/upstream-resolv.conf
systemctl daemon-reload
systemctl enable --now dnsmasq-virt
systemctl mask dnsmasq
-----

[#configure-local-dns-as-primary-server]
=== Configure Local DNS as Primary Server

The default upstream DNS is set to 1.1.1.1 in `/opt/dnsmasq/upstream-resolv.conf`. There might be cases in your local environment where the hypervisor may not reach it. So, notice that you must change it to a different DNS that allows you to resolve public hostnames. Once changed, remember to restart the dnsmasq-virt service.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
curl -L https://raw.githubusercontent.com/RHsyseng/telco-hypershift-baremetal-lab/lab-4.13/lab-materials/lab-env-data/hypervisor/forcedns -o /etc/NetworkManager/dispatcher.d/forcedns
chmod +x /etc/NetworkManager/dispatcher.d/forcedns
systemctl restart NetworkManager
/etc/NetworkManager/dispatcher.d/forcedns
-----

[#disable-firewall]
=== Disable Firewall

You can also create the required rules in the firewall if you want, but for the sake of simplicity we are disabling the firewall.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
systemctl disable firewalld iptables
systemctl stop firewalld iptables
iptables -F
-----

[#install-sushytools]
=== Install Sushy Tools

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
curl -L https://gist.githubusercontent.com/mvazquezc/0acb9e716c329abb9a184f1bcceed591/raw/4ae558082a3289d5d46be7d745bc2474e834e238/deploy-sushy-tools.sh -o /tmp/deploy-sushy-tools.sh
chmod +x /tmp/deploy-sushy-tools.sh
/tmp/deploy-sushy-tools.sh
-----

[#configure-ntp-server]
=== Configure NTP Server

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf install chrony -y
cat <<EOF > /etc/chrony.conf
server time.cloudflare.com iburst
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
keyfile /etc/chrony.keys
leapsectz right/UTC
logdir /var/log/chrony
bindcmdaddress ::
allow 192.168.125.0/24
EOF
systemctl enable chronyd --now
-----

[#configure-access-to-cluster-apps]
=== Configure Access to Cluster Apps

In order to access the hub cluster we will deploy an HAProxy that will be listening on the public interface of the Hypervisor host.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
dnf install haproxy -y
semanage port -a -t http_port_t -p tcp 6443
curl -L https://raw.githubusercontent.com/RHsyseng/telco-hypershift-baremetal-lab/lab-4.13/lab-materials/lab-env-data/haproxy/haproxy.cfg -o /etc/haproxy/haproxy.cfg
systemctl enable haproxy --now
-----

After that you need to add the following entries to your /etc/hosts file:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
<HYPERVISOR_REACHABLE_IP> infra.hypershift.lab api.management.hypershift.lab console-openshift-console.apps.management.hypershift.lab oauth-openshift.apps.management.hypershift.lab api.hosted.hypershift.lab console-openshift-console.apps.hosted.hypershift.lab oauth-hosted-hosted.apps.management.hypershift.lab
-----

[#create-openshift-nodes-vms]
=== Create OpenShift Nodes VMs

Before running the following commands, make sure you have generated a SSH key pair in your default location `~/.ssh/`. That SSH key will allow you to connect to the VMs you are about to create:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli create pool -p /var/lib/libvirt/images default
kcli create vm -P start=False -P uefi_legacy=true -P plan=lab -P memory=48000 -P numcpus=16 -P disks=[200,200] -P nets=['{"name": "hypershiftlab", "mac": "aa:aa:aa:aa:01:01"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0101 -P name=management-master0
kcli create vm -P start=False -P uefi_legacy=true -P plan=lab -P memory=48000 -P numcpus=16 -P disks=[200,200] -P nets=['{"name": "hypershiftlab", "mac": "aa:aa:aa:aa:01:02"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0102 -P name=management-master1
kcli create vm -P start=False -P uefi_legacy=true -P plan=lab -P memory=48000 -P numcpus=16 -P disks=[200,200] -P nets=['{"name": "hypershiftlab", "mac": "aa:aa:aa:aa:01:03"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0103 -P name=management-master2
kcli create vm -P start=False -P uefi_legacy=true -P plan=lab -P memory=24000 -P numcpus=12 -P disks=[200,200] -P nets=['{"name": "hypershiftlab", "mac": "aa:aa:aa:aa:02:01"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0201 -P name=hosted-worker0
kcli create vm -P start=False -P uefi_legacy=true -P plan=lab -P memory=24000 -P numcpus=12 -P disks=[200,200] -P nets=['{"name": "hypershiftlab", "mac": "aa:aa:aa:aa:02:02"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0202 -P name=hosted-worker1
kcli create vm -P start=False -P uefi_legacy=true -P plan=lab -P memory=24000 -P numcpus=12 -P disks=[200,200] -P nets=['{"name": "hypershiftlab", "mac": "aa:aa:aa:aa:02:03"}'] -P uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0203 -P name=hosted-worker2
systemctl restart sushy-tools
-----

If you need or want to connect to any of the VMs you can do so by just executing:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kcli ssh <VM_name>
-----

[#deploy-openshift-management-cluster]
=== Deploy OpenShift Management Cluster

IMPORTANT: This step requires a valid OpenShift Pull Secret placed in /root/openshift_pull.json. Notice that you can replace the admin or developer's password shown below for any other.

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
git clone https://github.com/karmab/kcli-openshift4-baremetal.git
curl -sL https://raw.githubusercontent.com/RHsyseng/telco-hypershift-baremetal-lab/lab-4.13/lab-materials/lab-env-data/management-cluster/management.yml -o /root/kcli-openshift4-baremetal/management.yml
cp /root/openshift_pull.json /root/kcli-openshift4-baremetal/openshift_pull.json
cd /root/kcli-openshift4-baremetal/
sed -i "s/CHANGE_ADMIN_PWD/admin/" management.yml
sed -i "s/CHANGE_DEV_PWD/developer/" management.yml
kcli create plan --pf management.yml --force
-----

This will take around 30-45m to complete, you can follow progress by running `kcli console -s`.

If the installation fails for whatever reason, you will need to delete all the VMs that were created and execute the same procedure again. So, first remove the plans, which actually will remove all VMs:

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----

# kcli list plan
+--------------------+-------------------------------------------------------------------------------------------------------+
|        Plan        |                                                  Vms                                                  |
+--------------------+-------------------------------------------------------------------------------------------------------+
|        lab         | hosted-worker0,hosted-worker1,hosted-worker2,management-master0,management-master1,management-master2 |
| management-cluster |                                          management-installer                                         |
+--------------------+-------------------------------------------------------------------------------------------------------+

# kcli delete plan management-cluster lab -y
management-installer deleted on local!
Plan management-cluster deleted!
hosted-worker0 deleted on local!
hosted-worker1 deleted on local!
hosted-worker2 deleted on local!
management-master0 deleted on local!
management-master1 deleted on local!
management-master2 deleted on local!
Plan lab deleted!
-----

And then create the VMs again as explained in the previous section link:lab-setup.html#create-openshift-nodes-vms[Deploy OpenShift Hub Cluster].

[#configure-openshift-management-cluster]
=== Configure OpenShift Management Cluster

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
cd ~
kcli ssh management-installer -- "sudo cp /root/ocp/auth/kubeconfig /tmp/kubeconfig && sudo chmod 644 /tmp/kubeconfig"
kcli scp management-installer:/tmp/kubeconfig ~/management-kubeconfig
export KUBECONFIG=~/management-kubeconfig
oc apply -f https://raw.githubusercontent.com/RHsyseng/telco-hypershift-baremetal-lab/lab-4.13/lab-materials/lab-env-data/management-cluster/lvmcluster.yaml
oc -n openshift-storage wait lvmcluster odf-lvmcluster --for=jsonpath='{.status.state}'=Ready --timeout=900s
oc patch storageclass lvms-vg1 -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
-----