= Metallb deployment
include::_attributes.adoc[]
:profile: telco-hypershift-baremetal-lab

In this section, we install Metallb operator and configure it so that our installation gets fully functional, through a loadbalancer ip  that will target our ingress service

[#install-metallb-operator]
== Install Metal LB operator

We inject the following yaml to deploy the operator

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator
  namespace: openshift-operators
spec:
  channel: "stable"
  name: metallb-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
-----

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
oc create -f scripts/METALLB/install.yaml
-----

Expected Output

```
subscription.operators.coreos.com/metallb-operator created
```

We can use the following loop to wait for the proper CRD to be available

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
timeout=0
ready=false
while [ "$timeout" -lt "240" ] ; do
  oc get crd | grep -q metallb && ready=true && break;
  echo "Waiting for CRD MetalLB to be created"
  sleep 5
  timeout=$(( $timeout + 5 ))
done
-----

Expectd Output

```
Waiting for CRD MetalLB to be created
Waiting for CRD MetalLB to be created
Waiting for CRD MetalLB to be created
Waiting for CRD MetalLB to be created
(...)
```

[#configure-metallb-operator]
== Configure Metal LB operator

We then define the following CR to deploy a metallb instance and create the proper configuration for our vip

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: openshift-operators
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: hypershift-vip
  namespace: openshift-operators
spec:
  protocol: layer2
  autoAssign: false
  addresses:
    - ${VIP}-${VIP}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: hypershift-vip
  namespace: openshift-operators
spec:
  ipAddressPools:
  - hypershift-vip
-----

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
export VIP=192.168.122.252
envsubst < scripts/METALLB/metallb_cr.yaml.sample | oc create -f -
-----

Expected Output

```
metallb.metallb.io/metallb created
ipaddresspool.metallb.io/hypershift-vip created
l2advertisement.metallb.io/default created
```

[#configure-ingress-service]
== Configure Ingress service

With this available load balancer ip, we will patch the ingress service on our deployed cluster so that it makes use of it

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
kind: Service
apiVersion: v1
metadata:
  annotations:
    metallb.universe.tf/address-pool: hypershift-vip
  name: metallb-ingress
  namespace: openshift-ingress
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: default
  type: LoadBalancer
-----

[.console-input]
[source,bash,subs="attributes+,+macros"]
-----
oc create -f scripts/METALLB/service.yaml
-----

Expected Output

```
service/metallb-ingress created
```

At this point, the cluster should be fully available!
